import {escape as e, localize as l, pathFor as url, idFor, paras, list, external, icon, readingTime, jsonScript} from './lib.mjs';

const labels = {
 fr:{home:'Accueil',projects:'Projets',journal:'Journal',skills:'Compétences',contact:'Contact',cv:'Voir le CV',skip:'Aller au contenu',theme:'Changer d’ambiance',day:'Jour',night:'Nuit',menu:'Menu',explore:'Explorer les projets',read:'Lire l’article',project:'Découvrir le projet',allProjects:'Tous les projets',allArticles:'Tout le journal',allSkills:'Toutes les compétences',role:'Mon rôle',scope:'Ma contribution',overview:'Le projet',gallery:'En images',related:'À lire sur ce projet',further:'Pour continuer',toc:'Dans cet article',intro:'Introduction',takeaway:'Ce que je retiens',share:'Copier le lien',copy:'Copier l’adresse',copied:'Copié',copyFailed:'Copie indisponible : sélectionnez le texte',reading:'min de lecture',search:'Chercher un sujet, un projet…',all:'Tout',results:'résultat(s)',empty:'Aucun résultat pour cette recherche',reset:'Effacer les filtres',filter:'Filtrer par domaine',design:'Design',qa:'QA',production:'Production',notes:'Carnets',legal:'Mentions légales',motion:'Animations actives',motionOff:'Animations en pause',systemMotion:'Animations réduites par votre système',close:'Fermer',previous:'Image précédente',next:'Image suivante',back:'Retour au journal',publicImage:'Visuels du projet, propriété de leurs auteurs respectifs',about:'Mon approche',footer:'Du design, des jeux, et ce qui les relie',case:'Étude de cas',note:'Note',devlog:'Carnet de développement',article:'Article',profile:'Un parcours à la croisée des métiers',evidence:'Dans la pratique',open:'Agrandir le visuel',studio:'Studio',details:'Repères',tools:'Outils & langues',top:'Retour en haut',download:'CV en français · PDF',technical:'Cette page reste lisible sans JavaScript'},
 en:{home:'Home',projects:'Projects',journal:'Journal',skills:'Skills',contact:'Contact',cv:'View resume',skip:'Skip to content',theme:'Change atmosphere',day:'Day',night:'Night',menu:'Menu',explore:'Explore the projects',read:'Read the article',project:'Explore the project',allProjects:'All projects',allArticles:'All journal entries',allSkills:'All skills',role:'My role',scope:'My contribution',overview:'The project',gallery:'In pictures',related:'More about this project',further:'Keep exploring',toc:'In this article',intro:'Introduction',takeaway:'What I take away',share:'Copy link',copy:'Copy email',copied:'Copied',copyFailed:'Copy unavailable: please select the text',reading:'min read',search:'Search a topic, a project…',all:'All',results:'result(s)',empty:'No results for this search',reset:'Clear filters',filter:'Filter by discipline',design:'Design',qa:'QA',production:'Production',notes:'Notes',legal:'Legal notice',motion:'Animations on',motionOff:'Animations paused',systemMotion:'Motion reduced by your system',close:'Close',previous:'Previous image',next:'Next image',back:'Back to journal',publicImage:'Project visuals belong to their respective authors',about:'My approach',footer:'Design, games, and everything in between',case:'Case study',note:'Note',devlog:'Devlog',article:'Article',profile:'A background across disciplines',evidence:'In practice',open:'Enlarge image',studio:'Studio',details:'At a glance',tools:'Tools & languages',top:'Back to top',download:'French resume · PDF',technical:'This page remains readable without JavaScript'}
};

/** Generate all pages using the same components, in both languages. */
export function makePages(model, media) {
 const {site, projects, articles, skills, editorial} = model;
 const pages=[];
 for (const lang of ['fr','en']) {
  const t=labels[lang], s=site[lang], home=url(lang);
  const projectByID = id => projects.find(p=>p.id===id);
  const title = v => e(l(v,lang));
  const typeName = a => ({'case-study':t.case, note:t.note, devlog:t.devlog, article:t.article})[a.type || 'case-study'] || t.article;
  const category = p => editorial.projects[p.id]?.category || p.category || 'design';
  const articleCategory = a => a.category || category(projectByID((a.projects || [])[0]) || {id:''});
  const articleTitle = a => l(editorial.articles[a.id]?.cardTitle || a.title,lang);
  const tag = text => `<span class="tag">${e(text)}</span>`;
  const paragraph = v => paras(l(v,lang));
  const textLink=(href,text,cls='text-link')=>`<a class="${cls}" href="${href}">${e(text)} ${icon('arrow')}</a>`;
  const crumb=(name,href)=>`<nav class="breadcrumbs" aria-label="${lang==='fr'?'Fil d’Ariane':'Breadcrumb'}"><a href="${home}">${t.home}</a><span aria-hidden="true">/</span>${href?`<a href="${href}">${e(name)}</a>`:`<span aria-current="page">${e(name)}</span>`}</nav>`;
  const sectionHead=(number,kicker,heading,desc,link='')=>`<div class="section-heading"><div><div class="eyebrow"><span class="section-number">${number}</span>${e(kicker)}</div><h2>${e(heading)}</h2>${desc?`<p>${e(desc)}</p>`:''}</div>${link}</div>`;
  const projectCard=(p,index,feature=false)=>{
   const ed=editorial.projects[p.id] || {}, href=url(lang,'project',p.id);
   return `<article class="project-card ${feature?'project-feature':''}" data-card data-category="${e(category(p))}" data-search="${e([l(p.title,lang),l(p.role,lang),...l(p.tags,lang),l(p.summary,lang)].join(' '))}"><a class="project-cover" href="${href}" tabindex="-1" aria-hidden="true">${media(p.images.cover,{alt:'',sizes:feature?'(max-width: 760px) 95vw, 64vw':'(max-width: 760px) 90vw, 35vw'})}<span class="image-index">${String(index+1).padStart(2,'0')}</span><span class="image-arrow">${icon('external')}</span></a><div class="project-copy"><div class="eyebrow small">${e(ed.studio || l(p.projectInfo?.developer,lang))}</div><h3><a href="${href}">${title(p.title)}</a></h3><p class="project-role">${title(p.role)}</p><p class="project-summary">${title(ed.cardSummary || p.summary)}</p><div class="tags">${l(p.tags,lang).slice(0,feature?3:2).map(tag).join('')}</div>${textLink(href,t.project)}</div></article>`;
  };
  const articleCard=(a,index=0)=>{
   const ed=editorial.articles[a.id] || {}, related=(a.projects||[]).map(projectByID).filter(Boolean), image=a.cover || a.media?.images?.[0] || related[0]?.images.cover || site.artwork.day;
   return `<article class="journal-card" data-card data-category="${e(articleCategory(a))}" data-search="${e([l(a.title,lang),l(a.abstract,lang),articleTitle(a),...(a.tags||[]),...related.map(p=>l(p.title,lang))].join(' '))}"><a class="journal-image" href="${url(lang,'article',a.id)}" tabindex="-1" aria-hidden="true">${media(image,{alt:'',sizes:'(max-width: 760px) 90vw, 35vw'})}<span class="journal-stamp">${String(index+1).padStart(2,'0')}</span></a><div class="journal-meta"><span>${typeName(a)}</span><span>${readingTime(l(a.article,lang))} ${t.reading}</span></div><h3><a href="${url(lang,'article',a.id)}">${e(articleTitle(a))}</a></h3><p>${title(ed.cardSummary || a.abstract)}</p><div class="journal-bottom"><span>${related.length ? related.map(p=>e(l(p.title,lang))).join(' · ') : e(a.timeframe || t.note)}</span>${textLink(url(lang,'article',a.id),t.read)}</div></article>`;
  };
  const contact=()=>`<section class="contact-block section wrap" id="contact" aria-labelledby="contact-title"><div class="contact-left"><div class="eyebrow"><span class="section-number">04</span>${t.contact}</div><h2 id="contact-title">${e(s.contactTitle).replaceAll('\n','<br>')}</h2><p>${e(s.contactText)}</p></div><div class="contact-right"><span class="eyebrow small">${e(site.location)}</span><a class="contact-email" href="mailto:${e(site.email)}">${e(site.email)} ${icon('external')}</a><button class="copy-button" data-copy="${e(site.email)}" hidden>${icon('copy')}<span>${t.copy}</span></button><div class="contact-socials">${site.social.map(x=>external(x.url,x.label)).join('')}</div><p class="muted">${e(s.contactNote)}</p></div></section>`;
  const gallery=(images,caption='')=>images?.length?`<figure class="gallery-figure"><div class="gallery" aria-label="${t.gallery}">${images.map((src,i)=>`<a class="gallery-item" href="${media.url(src)}" data-lightbox data-caption="${e(caption || t.publicImage)}" aria-label="${t.open} ${i+1}">${media(src,{alt:caption || `${t.gallery} ${i+1}`,sizes:'(max-width: 760px) 85vw, 600px'})}<span>${String(i+1).padStart(2,'0')} / ${String(images.length).padStart(2,'0')} ${icon('external')}</span></a>`).join('')}</div><figcaption>${e(caption || t.publicImage)}</figcaption></figure>`:'';
  const blocks=items=>(items||[]).map(b=>b.type==='callout'?`<aside class="callout"><h3>${e(b.title)}</h3>${paras(b.text)}</aside>`:b.type==='quote'?`<blockquote>${paras(b.text)}${b.author?`<cite>${e(b.author)}</cite>`:''}</blockquote>`:b.type==='image'?gallery([b.src],b.caption):b.type==='code'?`<pre><code>${e(b.text)}</code></pre>`:paras(b.text)).join('');
  const filter=(items,getCategory)=>{
   const cats=[...new Set(items.map(getCategory))];
   return `<div class="filter-bar" data-enhance hidden><div class="filter-chips" role="group" aria-label="${t.filter}"><button class="filter-chip" data-filter="all" aria-pressed="true">${t.all}<span>${items.length}</span></button>${cats.map(c=>`<button class="filter-chip" data-filter="${e(c)}" aria-pressed="false">${e(t[c] || c)}<span>${items.filter(x=>getCategory(x)===c).length}</span></button>`).join('')}</div><label class="search-field">${icon('search')}<span class="sr-only">${t.search}</span><input type="search" placeholder="${t.search}" data-search-input autocomplete="off"></label></div><p class="sr-only" data-results aria-live="polite"></p><div class="empty-state" data-empty hidden><p>${t.empty}</p><button class="button" data-reset>${t.reset}</button></div>`;
  };
  const expertise=(group,index,compact=false)=>{
   if(!group) return '';
   const examples=[...new Set(group.items.flatMap(i=>i.related?.projects||[]))].map(projectByID).filter(Boolean);
   const summaries=lang==='fr'?['Imaginer des parcours lisibles, travailler le rythme et donner au joueur la liberté d’expérimenter.','Transformer les intentions en priorités, en tâches et en décisions partagées.','Lire les frictions, organiser les retours et suivre les corrections jusqu’à la livraison.']:['Build readable routes, shape pacing and give players the freedom to experiment.','Turn intentions into priorities, tasks and shared decisions.','Read friction, organise feedback and track fixes through to release.'];
   return `<article class="expertise-card"><span class="expertise-symbol">${icon(index===0?'compass':index===1?'arrow':'check')}</span><span class="eyebrow small">${String(index+1).padStart(2,'0')}</span><h3>${e(group.cat)}</h3><p>${e(summaries[index] || group.items[0]?.summary)}</p><div class="evidence-label">${t.evidence}</div><div class="evidence-links">${examples.slice(0,2).map(p=>textLink(url(lang,'project',p.id),l(p.title,lang))).join('')}</div>${textLink(`${url(lang,'skills')}#${idFor(group.cat)}`,lang==='fr'?'Explorer ces compétences':'Explore these skills')}</article>`;
  };
  function shell(body,{route,kind='',id='',pageTitle,desc=s.description,image=site.artwork.day,homePage=false,reading=false,noindex=false}){
   const alternate=url(lang==='fr'?'en':'fr',kind,id), section=kind==='project'?'projects':kind==='article'?'journal':kind==='skills'?'skills':'';
   const navItems=[['projects',t.projects],['journal',t.journal],['skills',t.skills],['contact',t.contact]];
   const header=`<header class="site-header" id="top"><div class="header-inner"><a class="brand" href="${home}" aria-label="Nathan Tandille, ${t.home}"><span class="brand-mark">${icon('leaf')}</span><span><strong>Nathan Tandille</strong><span class="brand-sub">Level designer</span></span></a><nav class="primary-nav" id="primary-nav" aria-label="${t.menu}">${navItems.map(([anchor,name])=>`<a href="${home}#${anchor}" ${section===anchor?'aria-current="location"':''}>${name}</a>`).join('')}</nav><div class="header-actions"><a href="/${e(site.cv)}" class="cv-link" target="_blank" rel="noopener" title="${t.download}">CV ${icon('external')}</a><span class="action-divider"></span><button class="theme-button" data-theme-toggle aria-label="${t.theme}" title="${t.theme}" hidden><span class="day-icon">${icon('sun')}</span><span class="night-icon">${icon('moon')}</span></button><a class="language-switch" href="${alternate}" hreflang="${lang==='fr'?'en':'fr'}" lang="${lang==='fr'?'en':'fr'}" aria-label="${lang==='fr'?'Read this page in English':'Lire cette page en français'}">${lang==='fr'?'EN':'FR'}</a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav" aria-label="${t.menu}" hidden>${icon('menu')}</button></div></div><div class="reading-progress" aria-hidden="true"><span data-progress></span></div></header>`;
   const tree=`<div class="world-decoration" aria-hidden="true"><div class="world-tree" aria-hidden="true">${media(site.artwork.treeDay,{alt:'',className:'tree-day',sizes:'600px'})}${media(site.artwork.treeNight,{alt:'',className:'tree-night',sizes:'600px'})}</div><canvas class="leaf-canvas" aria-hidden="true"></canvas></div>`;
   const footer=`<footer class="site-footer wrap"><a class="footer-brand" href="${home}">${icon('leaf')}<span>Nathan Tandille<small>${e(t.footer)}</small></span></a><div class="footer-right"><button class="motion-toggle" data-motion-toggle aria-pressed="true" hidden>${icon('pause')}<span>${t.motion}</span></button><a href="${url(lang,'legal')}">${t.legal}</a><a href="#top" class="back-top" aria-label="${t.top}">${icon('down')}</a><span class="copyright">© ${new Date().getUTCFullYear()} Nathan Tandille</span></div></footer>`;
   const cfg={...t,lang,home,sprites:{day:media.url(site.artwork.leavesDay),night:media.url(site.artwork.leavesNight)},legacy:homePage?{projects:Object.fromEntries(projects.map(p=>[p.id,url(lang,'project',p.id)])),articles:Object.fromEntries(articles.map(a=>[a.id,url(lang,'article',a.id)]))}:undefined};
   const schema={'@context':'https://schema.org','@type':reading?'Article':'WebPage',name:pageTitle,url:site.url+route,inLanguage:lang,description:desc,author:{'@type':'Person',name:site.name,url:site.url}};
   const html=`<!doctype html><html lang="${lang}" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(pageTitle)} | Nathan Tandille</title><meta name="description" content="${e(desc)}"><meta name="theme-color" content="#f5f3e9"><link rel="canonical" href="${site.url+route}"><link rel="alternate" hreflang="${lang}" href="${site.url+route}"><link rel="alternate" hreflang="${lang==='fr'?'en':'fr'}" href="${site.url+alternate}"><meta property="og:type" content="${reading?'article':'website'}"><meta property="og:title" content="${e(pageTitle)} | Nathan Tandille"><meta property="og:description" content="${e(desc)}"><meta property="og:image" content="${site.url+media.url(image)}"><meta property="og:url" content="${site.url+route}"><meta name="twitter:card" content="summary_large_image">${noindex?'<meta name="robots" content="noindex">':''}<link rel="icon" href="/assets/favicon.svg"><script>try{let t=localStorage.getItem('pref-theme');document.documentElement.dataset.theme=t==='light'||t==='dark'?t:matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';if(localStorage.getItem('pref-motion')==='off'||matchMedia('(prefers-reduced-motion: reduce)').matches)document.documentElement.dataset.motion='off'}catch(e){}</script><link rel="stylesheet" href="/style.css"><script type="application/ld+json">${jsonScript(schema)}</script></head><body class="${homePage?'home-page':'inner-page'} ${reading?'article-page':''}"><a class="skip-link" href="#main">${t.skip}</a>${header}${tree}<main id="main" tabindex="-1">${body}</main>${footer}<div class="toast" role="status" aria-live="polite" hidden></div><dialog class="lightbox" aria-label="${t.gallery}"><button class="lightbox-close icon-button" data-close aria-label="${t.close}">${icon('close')}</button><button class="lightbox-prev icon-button" data-prev aria-label="${t.previous}">${icon('arrow')}</button><figure><img alt="" width="1600" height="1000"><figcaption></figcaption></figure><button class="lightbox-next icon-button" data-next aria-label="${t.next}">${icon('arrow')}</button></dialog><script id="site-config" type="application/json">${jsonScript(cfg)}</script><script src="/app.js" defer></script></body></html>`;
   pages.push({path:route,html});
  }

  const hero=`<section class="hero-shell"><div class="hero-frame"><div class="hero-scene" aria-hidden="true">${media(site.artwork.day,{alt:'',className:'hero-day',priority:true,sizes:'95vw'})}${media(site.artwork.night,{alt:'',className:'hero-night',sizes:'95vw'})}<div class="hero-wash"></div></div><div class="hero-content"><p class="hero-kicker">${e(s.heroKicker)}</p><h1>${e(s.heroTitle).replaceAll('\n','<br>')}<span class="heading-dot">.</span></h1><p class="hero-description">${e(s.heroDescription)}</p><div class="hero-actions">${textLink('#projects',t.explore,'button button-primary')}${textLink('/'+site.cv,t.cv,'button button-light')}</div></div><div class="hero-corner" aria-hidden="true">NT<br><span>PORTFOLIO</span></div></div><div class="hero-caption"><span>${e(s.heroNote)}</span><a href="#projects">${lang==='fr'?'Au fil des projets':'Through the projects'} ${icon('down')}</a></div></section>`;
  const pHome=projects.slice(0,site.homeProjectLimit);
  const homeBody=hero+`<section class="section wrap" id="projects">${sectionHead('01',t.projects,s.projectsTitle,s.projectsIntro,textLink(url(lang,'project'),t.allProjects))}<div class="project-grid">${pHome.map((p,i)=>projectCard(p,i,i===0)).join('')}</div></section><section class="journal-section" id="journal"><div class="wrap section">${sectionHead('02',t.journal,s.journalTitle,s.journalIntro,textLink(url(lang,'article'),t.allArticles))}<div class="journal-grid">${articles.slice(0,site.homeArticleLimit).map(articleCard).join('')}</div></div></section><section class="section wrap" id="skills">${sectionHead('03',t.skills,s.skillsTitle,s.skillsIntro,textLink(url(lang,'skills'),t.allSkills))}<div class="expertise-grid">${skills[lang].slice(0,3).map((g,i)=>expertise(g,i,true)).join('')}</div><div class="about-note"><div class="about-title"><span class="eyebrow">${t.about}</span><h3>${e(s.aboutTitle).replaceAll('\n','<br>')}</h3></div><div><p>${e(s.aboutText)}</p>${external('/'+site.cv,t.cv)}</div></div></section>${contact()}`;
  shell(homeBody,{route:home,pageTitle:'Level Designer',homePage:true});
  shell(`<div class="wrap archive-head">${crumb(t.projects)}<div class="eyebrow">01 / ${t.projects}</div><h1>${e(s.projectsTitle)}</h1><p class="lead">${e(s.projectsIntro)}</p></div><section class="wrap archive-body" data-filterable>${filter(projects,category)}<div class="project-grid archive-grid">${projects.map((p,i)=>projectCard(p,i)).join('')}</div></section>${contact()}`,{route:url(lang,'project'),kind:'project',pageTitle:t.projects});
  shell(`<div class="wrap archive-head">${crumb(t.journal)}<div class="eyebrow">02 / ${t.journal}</div><h1>${e(s.journalTitle)}</h1><p class="lead">${e(s.journalIntro)}</p></div><section class="wrap archive-body" data-filterable>${filter(articles,articleCategory)}<div class="journal-grid">${articles.map(articleCard).join('')}</div></section>${contact()}`,{route:url(lang,'article'),kind:'article',pageTitle:t.journal});
  for(const p of projects){
   const related=articles.filter(a=>(a.projects||[]).includes(p.id)), facts=l(p.facts,lang)||[], info=p.projectInfo||{};
   const body=`<div class="wrap detail-head">${crumb(t.projects,url(lang,'project'))}<div class="eyebrow">${title(p.role)}<span>·</span>${e(editorial.projects[p.id]?.studio || l(info.developer,lang))}</div><h1>${title(p.title)}</h1><p class="lead">${title(p.summary)}</p><div class="tags">${l(p.tags,lang).map(tag).join('')}</div></div><div class="wrap project-hero">${media(p.images.cover,{alt:l(p.title,lang),priority:true,sizes:'90vw'})}</div><div class="wrap"><dl class="facts">${facts.map(f=>`<div><dt>${e(f.label)}</dt><dd>${e(f.value)}</dd></div>`).join('')}</dl></div><div class="wrap project-body"><article class="prose"><section id="overview"><div class="eyebrow">${t.overview}</div><h2>${t.overview}</h2>${paragraph(info.description)}${paragraph(p.overview)}</section><section id="contribution"><h2>${t.scope}</h2><ul>${list(l(p.contribution,lang))}</ul></section></article><aside class="project-aside"><h2>${t.details}</h2><dl>${[['developer',t.studio],['publisher',lang==='fr'?'Éditeur':'Publisher'],['engine',lang==='fr'?'Moteur':'Engine'],['platforms',lang==='fr'?'Plateformes':'Platforms'],['releaseDate',lang==='fr'?'Sortie':'Release'],['genres',lang==='fr'?'Genre':'Genre'],['languages',lang==='fr'?'Langues du jeu':'Game languages']].filter(([k])=>info[k]).map(([k,name])=>`<div><dt>${name}</dt><dd>${title(info[k])}</dd></div>`).join('')}</dl><div class="aside-links">${(p.links||[]).map(x=>external(x.url,l(x.label,lang))).join('')}${p.trailer?external(p.trailer,lang==='fr'?'Voir la bande-annonce':'Watch the trailer'):''}</div></aside></div><section class="wrap gallery-section"><h2>${t.gallery}</h2>${gallery(p.images.gallery)}</section>${related.length?`<section class="section wrap">${sectionHead('↳',t.journal,t.related,'')}<div class="journal-grid related-grid">${related.map(articleCard).join('')}</div></section>`:''}<div class="wrap return-row">${textLink(url(lang,'project'),t.allProjects)}${textLink(home+'#contact',t.contact)}</div>`;
   shell(body,{route:url(lang,'project',p.id),kind:'project',id:p.id,pageTitle:l(p.title,lang),desc:l(p.summary,lang),image:p.images.cover});
  }
  for(const a of articles){
   const data=l(a.article,lang), sections=data.sections||[], related=(a.projects||[]).map(projectByID).filter(Boolean), image=a.cover||a.media?.images?.[0]||related[0]?.images.cover||site.artwork.day;
   const toc=[['introduction',t.intro],...sections.map((x,i)=>[`section-${i+1}`,x.heading]),...(data.blocks?.length?[['notes',lang==='fr'?'Points à retenir':'Key points']]:[]),...(data.closing?[['conclusion',t.takeaway]]:[])];
   const body=`<div class="wrap detail-head article-head">${crumb(t.journal,url(lang,'article'))}<div class="eyebrow">${typeName(a)}${a.timeframe?`<span>·</span>${e(a.timeframe)}`:''}${a.date?`<time datetime="${e(a.date)}">${new Date(a.date).toLocaleDateString(lang==='fr'?'fr-FR':'en-GB',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'})}</time>`:''}</div><h1>${title(a.title)}</h1><p class="lead">${title(a.abstract)}</p><div class="article-meta"><span>Nathan Tandille</span><span>${readingTime(data)} ${t.reading}</span><button class="copy-button" data-copy-url hidden>${icon('copy')}${t.share}</button></div><div class="tags">${related.map(p=>`<a class="tag tag-link" href="${url(lang,'project',p.id)}">${title(p.title)} ${icon('external')}</a>`).join('')}${(a.tags||[]).map(tag).join('')}</div></div><div class="wrap article-cover">${media(image,{alt:l(a.title,lang),priority:true,sizes:'90vw'})}</div><div class="wrap reading-layout"><aside class="toc"><details open><summary>${t.toc}</summary><nav aria-label="${t.toc}">${toc.map(([id,name],i)=>`<a href="#${id}"><span>${String(i+1).padStart(2,'0')}</span>${e(name)}</a>`).join('')}</nav></details>${textLink(url(lang,'article'),t.back)}</aside><article class="prose article-prose" data-reading><section id="introduction" data-toc-section><h2 class="sr-only">${t.intro}</h2>${paras(data.intro)}${a.role?`<p class="role-note"><strong>${t.role}</strong> ${title(a.role)}</p>`:''}${a.metrics?.length?`<dl class="article-metrics">${a.metrics.map(m=>`<div><dt>${title(m.label)}</dt><dd>${e(m.value)}</dd></div>`).join('')}</dl>`:''}</section>${sections.map((x,i)=>`<section id="section-${i+1}" data-toc-section><span class="section-counter">${String(i+1).padStart(2,'0')}</span><h2>${e(x.heading)}</h2>${paras(x.paragraphs)}${x.bullets?.length?`<ul>${list(x.bullets)}</ul>`:''}${x.media?gallery(x.media.images||[x.media.src].filter(Boolean),l(x.media.caption,lang)):''}${blocks(x.blocks)}</section>`).join('')}${data.blocks?.length?`<section id="notes" data-toc-section><h2>${lang==='fr'?'Points à retenir':'Key points'}</h2>${blocks(data.blocks)}</section>`:''}${data.closing?`<section id="conclusion" class="conclusion" data-toc-section><h2>${t.takeaway}</h2>${paras(data.closing)}</section>`:''}</article></div>${related.length?`<section class="section wrap">${sectionHead('↳',t.projects,lang==='fr'?'Le projet, en contexte':'The project in context','')}<div class="project-grid archive-grid">${related.map((p,i)=>projectCard(p,i)).join('')}</div></section>`:''}<div class="wrap return-row">${textLink(url(lang,'article'),t.back)}${textLink(home+'#contact',t.contact)}</div>`;
   shell(body,{route:url(lang,'article',a.id),kind:'article',id:a.id,pageTitle:l(a.title,lang),desc:l(a.abstract,lang),image,reading:true});
  }
  const skillsBody=`<div class="wrap archive-head">${crumb(t.skills)}<div class="eyebrow">03 / ${t.skills}</div><h1>${e(s.skillsTitle)}</h1><p class="lead">${e(s.skillsIntro)}</p></div><div class="wrap skills-directory"><nav class="skills-index" aria-label="${t.skills}">${skills[lang].map((g,i)=>`<a href="#${idFor(g.cat)}"><span>${String(i+1).padStart(2,'0')}</span>${e(g.cat)}</a>`).join('')}</nav><div>${skills[lang].map((g,i)=>`<section class="skill-category" id="${idFor(g.cat)}"><div class="eyebrow">${String(i+1).padStart(2,'0')}</div><h2>${e(g.cat)}</h2>${g.items.map(item=>`<details class="skill-item" id="${e(item.id)}"><summary><span><strong>${e(item.name)}</strong><span class="skill-summary">${e(item.summary)}</span></span><span class="expand-icon" aria-hidden="true">+</span></summary><div class="skill-content">${item.bullets?.length?`<ul>${list(item.bullets)}</ul>`:''}<div class="tags">${(item.tags||[]).map(tag).join('')}</div><div class="skill-related">${(item.related?.projects||[]).map(projectByID).filter(Boolean).map(p=>textLink(url(lang,'project',p.id),l(p.title,lang))).join('')}${(item.related?.cases||[]).map(id=>articles.find(a=>a.id===id)).filter(Boolean).map(a=>textLink(url(lang,'article',a.id),articleTitle(a))).join('')}</div>${gallery(item.images?.filter(src => typeof src === 'string' && src.startsWith('assets/')).slice(0,2))}</div></details>`).join('')}</section>`).join('')}</div></div>${contact()}`;
  shell(skillsBody,{route:url(lang,'skills'),kind:'skills',pageTitle:t.skills});
  const legalBody=`<div class="wrap archive-head">${crumb(t.legal)}<h1>${t.legal}</h1></div><article class="wrap prose legal-prose"><h2>${lang==='fr'?'Éditeur du site':'Site publisher'}</h2><p>Nathan Tandille · ${lang==='fr'?'Portfolio non commercial':'Non-commercial portfolio'}</p><p><a href="mailto:${e(site.email)}">${e(site.email)}</a></p><h2>${lang==='fr'?'Hébergement':'Hosting'}</h2><p>Vercel</p><h2>${lang==='fr'?'Contenus et visuels':'Content and visuals'}</h2><p>${lang==='fr'?'Les marques et les visuels des jeux restent la propriété de leurs auteurs et ayants droit respectifs. Les visuels illustrent les projets et ne constituent pas, à eux seuls, une attribution de leur création à Nathan Tandille.':'Game brands and visuals belong to their respective authors and rights holders. Images illustrate the projects and do not, by themselves, imply that Nathan Tandille created them.'}</p><h2>${lang==='fr'?'Vie privée':'Privacy'}</h2><p>${lang==='fr'?'Ce site n’intègre ni outil publicitaire, ni analyse d’audience tierce, ni formulaire de collecte. Les préférences d’ambiance et d’animation sont mémorisées localement dans votre navigateur. Les liens externes vous dirigent vers les services concernés, qui appliquent leurs propres politiques de confidentialité.':'This site includes no advertising, third-party analytics or data collection form. Theme and motion preferences are stored locally in your browser. External links lead to services with their own privacy policies.'}</p></article>`;
  shell(legalBody,{route:url(lang,'legal'),kind:'legal',pageTitle:t.legal});
 }
 return pages;
}
